import type { Metadata } from "next";
import React,{Suspense} from "react";

import local from 'next/font/local';
const Footer = React.lazy(()=>import('@/components/shared/Footer/Footer'))
const Navbar = React.lazy(()=>import('@/components/shared/Navbar/navbar'))
import "./globals.css";

const TitilliumWeb = local({
  src: [{
    path: '../public/fonts/Titillium_Web/TitilliumWeb-Light.ttf',
    weight: "400",
  }
  ],
  variable: "--TitilliumWeb",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${TitilliumWeb.className}`}>
     <Navbar />
     <div className="min-h-[75vh] bg-white" >
     {children}
        </div>
        <Footer />
        </body>
    </html>
  );  
}
